/* tslint:disable */
/* eslint-disable */
/**
 * N8Ik Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface DeploymentCreateSchema {
    'name'?: string | null;
    /**
     * CPU in kubernetes millicores
     */
    'cpu'?: number;
    /**
     * Memory in MB
     */
    'memory'?: number;
    /**
     * Configuration settings for the deployment
     */
    'deployment_config': N8ndeploymentSchema;
}
export interface DeploymentSchema {
    /**
     * Unique identifier for the entity
     */
    'uid'?: string;
    /**
     * Date and time the entity was created
     */
    'created_at'?: string;
    /**
     * Date and time the entity was last updated
     */
    'updated_at'?: string;
    /**
     * Whether the entity has been deleted
     */
    'is_deleted'?: boolean;
    'meta_data'?: { [key: string]: any; } | null;
    'user_id': string;
    'name'?: string | null;
    /**
     * CPU in kubernetes millicores
     */
    'cpu'?: number;
    /**
     * Memory in MB
     */
    'memory'?: number;
    /**
     * Configuration settings for the deployment
     */
    'deployment_config': N8ndeploymentSchema;
    /**
     * URI of the deployment
     */
    'uri': string;
    /**
     * Indicates whether the deployment is paused
     */
    'is_paused'?: boolean;
}
export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface LocationInner {
}
export interface N8ndeploymentSchema {
    /**
     * Indicates whether the deployment is enabled
     */
    'is_enabled'?: boolean;
    /**
     * Version of the deployment in docker format
     */
    'version'?: string;
    /**
     * Storage in MB
     */
    'storage'?: number;
    /**
     * CPU in kubernetes millicores
     */
    'cpu'?: number;
    /**
     * Memory in MB
     */
    'memory'?: number;
}
export interface PaginatedResponseDeploymentSchema {
    'heads'?: { [key: string]: { [key: string]: string; }; };
    'items': Array<DeploymentSchema>;
    'total': number;
    'offset': number;
    'limit': number;
}
export interface ValidationError {
    'loc': Array<LocationInner>;
    'msg': string;
    'type': string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Health check endpoint handler.  Args:     request: FastAPI request object.  Returns:     Dictionary with status \"up\".
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthApiN8ikV1HealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/n8ik/v1/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Health check endpoint handler.  Args:     request: FastAPI request object.  Returns:     Dictionary with status \"up\".
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthApiN8ikV1HealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthApiN8ikV1HealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthApiN8ikV1HealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Health check endpoint handler.  Args:     request: FastAPI request object.  Returns:     Dictionary with status \"up\".
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthApiN8ikV1HealthGet(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.healthApiN8ikV1HealthGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * Health check endpoint handler.  Args:     request: FastAPI request object.  Returns:     Dictionary with status \"up\".
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthApiN8ikV1HealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthApiN8ikV1HealthGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DeploymentsApi - axios parameter creator
 */
export const DeploymentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Item
         * @param {DeploymentCreateSchema} deploymentCreateSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createItemApiN8ikV1DeploymentsPost: async (deploymentCreateSchema: DeploymentCreateSchema, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentCreateSchema' is not null or undefined
            assertParamExists('createItemApiN8ikV1DeploymentsPost', 'deploymentCreateSchema', deploymentCreateSchema)
            const localVarPath = `/api/n8ik/v1/deployments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deploymentCreateSchema, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.  Returns:     Item.
         * @summary Delete Item
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteItemApiN8ikV1DeploymentsUidDelete: async (uid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('deleteItemApiN8ikV1DeploymentsUidDelete', 'uid', uid)
            const localVarPath = `/api/n8ik/v1/deployments/{uid}`
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List items endpoint handler.  Args:     request: FastAPI request object.     offset: Starting offset for pagination.     limit: Maximum number of items to return.     created_at_from: Optional start date filter.     created_at_to: Optional end date filter.  Returns:     PaginatedResponse with items and metadata.
         * @summary List Items
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {string | null} [createdAtFrom] 
         * @param {string | null} [createdAtTo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listItemsApiN8ikV1DeploymentsGet: async (offset?: number, limit?: number, createdAtFrom?: string | null, createdAtTo?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/n8ik/v1/deployments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (createdAtFrom !== undefined) {
                localVarQueryParameter['created_at_from'] = (createdAtFrom as any instanceof Date) ?
                    (createdAtFrom as any).toISOString() :
                    createdAtFrom;
            }

            if (createdAtTo !== undefined) {
                localVarQueryParameter['created_at_to'] = (createdAtTo as any instanceof Date) ?
                    (createdAtTo as any).toISOString() :
                    createdAtTo;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.  Returns:     Item.
         * @summary Retrieve Item
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveItemApiN8ikV1DeploymentsUidGet: async (uid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('retrieveItemApiN8ikV1DeploymentsUidGet', 'uid', uid)
            const localVarPath = `/api/n8ik/v1/deployments/{uid}`
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.     data: The data to update the item.  Returns:     Item.
         * @summary Update Item
         * @param {string} uid 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateItemApiN8ikV1DeploymentsUidPatch: async (uid: string, requestBody: { [key: string]: any; }, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('updateItemApiN8ikV1DeploymentsUidPatch', 'uid', uid)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('updateItemApiN8ikV1DeploymentsUidPatch', 'requestBody', requestBody)
            const localVarPath = `/api/n8ik/v1/deployments/{uid}`
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeploymentsApi - functional programming interface
 */
export const DeploymentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DeploymentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Item
         * @param {DeploymentCreateSchema} deploymentCreateSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createItemApiN8ikV1DeploymentsPost(deploymentCreateSchema: DeploymentCreateSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createItemApiN8ikV1DeploymentsPost(deploymentCreateSchema, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.createItemApiN8ikV1DeploymentsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.  Returns:     Item.
         * @summary Delete Item
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteItemApiN8ikV1DeploymentsUidDelete(uid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteItemApiN8ikV1DeploymentsUidDelete(uid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.deleteItemApiN8ikV1DeploymentsUidDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List items endpoint handler.  Args:     request: FastAPI request object.     offset: Starting offset for pagination.     limit: Maximum number of items to return.     created_at_from: Optional start date filter.     created_at_to: Optional end date filter.  Returns:     PaginatedResponse with items and metadata.
         * @summary List Items
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {string | null} [createdAtFrom] 
         * @param {string | null} [createdAtTo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listItemsApiN8ikV1DeploymentsGet(offset?: number, limit?: number, createdAtFrom?: string | null, createdAtTo?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResponseDeploymentSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listItemsApiN8ikV1DeploymentsGet(offset, limit, createdAtFrom, createdAtTo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.listItemsApiN8ikV1DeploymentsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.  Returns:     Item.
         * @summary Retrieve Item
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveItemApiN8ikV1DeploymentsUidGet(uid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveItemApiN8ikV1DeploymentsUidGet(uid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.retrieveItemApiN8ikV1DeploymentsUidGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.     data: The data to update the item.  Returns:     Item.
         * @summary Update Item
         * @param {string} uid 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateItemApiN8ikV1DeploymentsUidPatch(uid: string, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateItemApiN8ikV1DeploymentsUidPatch(uid, requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.updateItemApiN8ikV1DeploymentsUidPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DeploymentsApi - factory interface
 */
export const DeploymentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DeploymentsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Item
         * @param {DeploymentCreateSchema} deploymentCreateSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createItemApiN8ikV1DeploymentsPost(deploymentCreateSchema: DeploymentCreateSchema, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentSchema> {
            return localVarFp.createItemApiN8ikV1DeploymentsPost(deploymentCreateSchema, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.  Returns:     Item.
         * @summary Delete Item
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteItemApiN8ikV1DeploymentsUidDelete(uid: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentSchema> {
            return localVarFp.deleteItemApiN8ikV1DeploymentsUidDelete(uid, options).then((request) => request(axios, basePath));
        },
        /**
         * List items endpoint handler.  Args:     request: FastAPI request object.     offset: Starting offset for pagination.     limit: Maximum number of items to return.     created_at_from: Optional start date filter.     created_at_to: Optional end date filter.  Returns:     PaginatedResponse with items and metadata.
         * @summary List Items
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {string | null} [createdAtFrom] 
         * @param {string | null} [createdAtTo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listItemsApiN8ikV1DeploymentsGet(offset?: number, limit?: number, createdAtFrom?: string | null, createdAtTo?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedResponseDeploymentSchema> {
            return localVarFp.listItemsApiN8ikV1DeploymentsGet(offset, limit, createdAtFrom, createdAtTo, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.  Returns:     Item.
         * @summary Retrieve Item
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveItemApiN8ikV1DeploymentsUidGet(uid: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentSchema> {
            return localVarFp.retrieveItemApiN8ikV1DeploymentsUidGet(uid, options).then((request) => request(axios, basePath));
        },
        /**
         * Update the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.     data: The data to update the item.  Returns:     Item.
         * @summary Update Item
         * @param {string} uid 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateItemApiN8ikV1DeploymentsUidPatch(uid: string, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentSchema> {
            return localVarFp.updateItemApiN8ikV1DeploymentsUidPatch(uid, requestBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeploymentsApi - object-oriented interface
 */
export class DeploymentsApi extends BaseAPI {
    /**
     * 
     * @summary Create Item
     * @param {DeploymentCreateSchema} deploymentCreateSchema 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createItemApiN8ikV1DeploymentsPost(deploymentCreateSchema: DeploymentCreateSchema, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).createItemApiN8ikV1DeploymentsPost(deploymentCreateSchema, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.  Returns:     Item.
     * @summary Delete Item
     * @param {string} uid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteItemApiN8ikV1DeploymentsUidDelete(uid: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).deleteItemApiN8ikV1DeploymentsUidDelete(uid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List items endpoint handler.  Args:     request: FastAPI request object.     offset: Starting offset for pagination.     limit: Maximum number of items to return.     created_at_from: Optional start date filter.     created_at_to: Optional end date filter.  Returns:     PaginatedResponse with items and metadata.
     * @summary List Items
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {string | null} [createdAtFrom] 
     * @param {string | null} [createdAtTo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listItemsApiN8ikV1DeploymentsGet(offset?: number, limit?: number, createdAtFrom?: string | null, createdAtTo?: string | null, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).listItemsApiN8ikV1DeploymentsGet(offset, limit, createdAtFrom, createdAtTo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.  Returns:     Item.
     * @summary Retrieve Item
     * @param {string} uid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public retrieveItemApiN8ikV1DeploymentsUidGet(uid: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).retrieveItemApiN8ikV1DeploymentsUidGet(uid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update the item for the USSO routes.  Args:     request: The request.     uid: The UID of the item.     data: The data to update the item.  Returns:     Item.
     * @summary Update Item
     * @param {string} uid 
     * @param {{ [key: string]: any; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateItemApiN8ikV1DeploymentsUidPatch(uid: string, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).updateItemApiN8ikV1DeploymentsUidPatch(uid, requestBody, options).then((request) => request(this.axios, this.basePath));
    }
}



